spring:
  application:
    name: currency-convertor-service

server:
  port: 8050
  
eureka:
  client:
    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
      defaultZone: http://eureka-service:8761/eureka/
  instance:
    preferIpAddress: true 